In [ ]:
# EXERCISES XP

In [13]:
import numpy as np

In [ ]:
#Exercise 1 : Create a 1D NumPy array containing numbers from 0 to 9, 



In [4]:
array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Exercise 2 : Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

In [ ]:



array_float = np.array([3.14, 2.17, 0, 1, 2])
array_int = array_float.astype(int)
array_int



array([3, 2, 0, 1, 2])

In [6]:
#Exercise 3 : Create a 3x3 NumPy array with values ranging from 1 to 9

array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# Exercise 4 : Create a 2D NumPy array of shape (4, 5) filled with random numbers.
array_random = np.random.rand(4, 5)
array_random

array([[0.7714388 , 0.16584885, 0.83155187, 0.58231397, 0.02750675],
       [0.52455658, 0.90269964, 0.82962835, 0.75601573, 0.81608047],
       [0.08951862, 0.22475916, 0.25150235, 0.60818932, 0.5266007 ],
       [0.04302021, 0.3695932 , 0.3713541 , 0.46657425, 0.26669766]])

In [10]:
# Exercise 5 :Select the second row from a given 2D NumPy array.
array_2d = np.array([[21, 22, 23, 22, 22],[20, 21, 22, 23, 24],[21, 22, 23, 22, 22]])
second_row = array_2d[1]        
second_row

array([20, 21, 22, 23, 24])

In [12]:
# Exercise 6 : Reverse the order of elements in a given 1D NumPy array (first element becomes last).



In [ ]:
import random
array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
new = np.random.permutation(array)
new

array([6, 1, 0, 5, 7, 2, 3, 4, 8, 9])

In [25]:
# Exercise : 7 : Create a 4x4 identity matrix using NumPy.
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# Exercise 8 :Find the sum and average of a given 1D array.
array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
array_sum = np.sum(array)
array_mean = np.mean(array)
print("Sum:", array_sum)
print("Average:", array_mean)

Sum: 45
Average: 4.5


In [37]:
# Exercise 9 :Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.
array = np.arange(1, 21).reshape(4, 5)
reshaped_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [28]:
# exercise 10 : Extract all odd numbers from a given NumPy array.
array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_numbers = array[array % 2 != 0]
odd_numbers

array([1, 3, 5, 7, 9])

In [ ]:
#EXERCISES XP GOLD 

In [ ]:
# Exercise 1 : Create a 5x5 array with random values and find the minimum and maximum values.
array = np.random.rand(5, 5)
min_value = np.min(array)   
max_value = np.max(array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.04937034590533684
Maximum value: 0.9711575594240541


In [38]:
# Exercise 2 :Normalize a 3x3 random matrix (subtract the mean and divide by the standard deviation of the matrix).
array_random = np.random.rand(3, 3)
mean = np.mean(array_random)
std = np.std(array_random)
normalized_array = (array_random - mean) / std if std != 0 else array_random - mean
normalized_array

array([[-1.0638781 ,  0.26493014,  1.79631877],
       [-1.48125268, -0.52269453,  0.034002  ],
       [ 0.76676205, -0.76128006,  0.9670924 ]])

In [39]:
# Exercise 3 : Create a 1D array of 50 evenly spaced elements between 0 and 10, exclusive.
evenly_spaced_array = np.linspace(0, 10, num=50, endpoint=False)
evenly_spaced_array

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6,
       7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [41]:
# Exercise 4 :Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).
matrix_a = np.random.rand(5, 3)
matrix_b = np.random.rand(3, 2)
product = matrix_a @ matrix_b
product


array([[0.81944677, 1.09552403],
       [0.48398231, 0.42033415],
       [0.1916841 , 0.60119373],
       [0.53501494, 1.17855126],
       [0.51271186, 0.32545805]])

In [42]:
# Exercise 5 :multiplication on these matrices
a = np.random.rand(5, 4)
b = np.random.rand(4, 3)
c = a @ b
c

array([[1.26602861, 0.73198014, 1.19772311],
       [0.91348056, 0.97314183, 0.89695506],
       [1.24676596, 1.24004623, 0.97135153],
       [0.67573093, 0.84777973, 0.56156431],
       [1.01232552, 1.02622961, 0.94558786]])

In [ ]:
# EXERCISE XP NINJA

In [7]:
# Exercise 1 : Create a random 5x5 matrix and replace the maximum valuem.rand() by 0
random_matrix = np.random.rand(5,5)
max_maximum = np.max(random_matrix)
random_matrix[random_matrix == max_maximum] =0
random_matrix



array([[0.54215273, 0.91023234, 0.68391523, 0.91987086, 0.9147593 ],
       [0.85771545, 0.80813925, 0.63857205, 0.24554647, 0.13076812],
       [0.9589487 , 0.46990981, 0.14027843, 0.60971927, 0.83907921],
       [0.88661438, 0.1723681 , 0.74560294, 0.30076514, 0.25607843],
       [0.27291271, 0.02080753, 0.01384152, 0.11523389, 0.        ]])

In [11]:
# Exercise 2 : Find the common values between two random arrays of size 5
array1 = np.random.rand(5)
array2 = np.random.rand(5)
common_values = np.intersect1d(array1, array2)
common_values

array([], dtype=float64)

In [16]:
# Exercise 3 :Create a random 1D array of size 10 and sort it in ascending and then in descending order
array = np.random.rand(10)
sorted_array_asc = np.sort(array)
sorted_array_descending = sorted_array_asc[::-1]
sorted_array_asc, sorted_array_descending



(array([0.15111626, 0.43994384, 0.52811492, 0.52847411, 0.69921904,
        0.73572485, 0.85954839, 0.86758305, 0.87300882, 0.87525031]),
 array([0.87525031, 0.87300882, 0.86758305, 0.85954839, 0.73572485,
        0.69921904, 0.52847411, 0.52811492, 0.43994384, 0.15111626]))

In [17]:
# Exercise 4 : Generate a random 4x4 matrix and find the rank of the matrix
random_matrix = np.random.rand(4, 4)
rank = np.linalg.matrix_rank(random_matrix)
rank

np.int64(4)

In [19]:
# Exercise 5 :Create a 2D array with 1 on the border and 0 inside
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0   
array

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])